name: "OpenWrt Install ISO"

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '请输入下载地址(扩展名 .img.gz/.img.xz/.img.zip)'
        required: true
        default: 'https://default.example.com/file.img.gz'

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: write # 必须赋予写入权限才能删除和创建 Release

    steps:
      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: Set executable permissions
        run: |
          chmod +x "${{ github.workspace }}/custom.sh"
          chmod +x "${{ github.workspace }}/supportFiles/custom/build.sh"

      - name: Validate Download URL
        run: |
          DEFAULT_URL="https://default.example.com/file.img.gz"
          USER_INPUT_URL="${{ github.event.inputs.download_url }}"
          
          if [[ "$USER_INPUT_URL" == "$DEFAULT_URL" ]]; then
            echo "❌ 错误：请修改默认下载地址！当前地址为无效占位符。"
            exit 1
          fi
          
          if [[ ! "$USER_INPUT_URL" =~ ^https?://.+\.[gG][zZ]$|^https?://.+\.[xX][zZ]$|^https?://.+\.[zZ][iI][pP]$ ]]; then
            echo "❌ 错误：地址需以 http(s) 开头且扩展名为 .gz/.xz/.zip"
            echo "当前输入：$USER_INPUT_URL"
            exit 1
          fi

      - name: "Build Image"
        run: |
          download_url="${{ github.event.inputs.download_url }}"
          ./custom.sh "$download_url"

      # 在发布前清理同名 Release 和 Tag ---
      - name: "Cleanup Existing Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "OpenWrt-Install-ISO" --cleanup-tag -y || true    

      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "OpenWrt-Install-ISO"
          body_path: "${{ github.workspace }}/supportFiles/custom/info.md"
          files: |
            output/openwrt-x86_64-install.iso
          token: "${{ secrets.GITHUB_TOKEN }}"
